coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%

comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

codecov:
  require_ci_to_pass: yes
